name: tennis
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  formz: ^0.4.1
  freezed_annotation: ^2.2.0
  gap: ^2.0.0
  provider: ^6.0.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  lint: ^1.10.0

flutter:
  uses-material-design: true
